logging:
  level:
    com.example.auth0cleanupsb: INFO

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
