server:
  port: 8080

spring:
  application:
    name: auth0-cleanup-app-sb

app:
  # If set, these override SSM; otherwise they are loaded from SSM path (paramPrefix)
  paramPrefix: "/auth0-cleanup/"      # SSM path (hierarchical)
  s3:
    bucket: ""                        # e.g. auth0-deleted-users
    key: "output/deleted_users.csv"
  auth0:
    domain: ""                        # e.g. dev-xxx.us.auth0.com (NO https://)
    audience: ""                      # e.g. https://dev-xxx.us.auth0.com/api/v2/
    clientId: ""
    clientSecret: ""
